# Generated by Django 5.1.2 on 2024-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
