# Generated by Django 5.1.2 on 2024-10-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_shipped",
            field=models.BooleanField(default=False),
        ),
    ]
