# Generated by Django 5.1.2 on 2024-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_order_is_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
