# Generated by Django 5.1.2 on 2024-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_order_shipped_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
